I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 231, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splashscreen.rpy", line 15, in script
    with dissove
  File "game/splashscreen.rpy", line 15, in <module>
    with dissove
NameError: name 'dissove' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 231, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splashscreen.rpy", line 15, in script
    with dissove
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/ast.py", line 1390, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/splashscreen.rpy", line 15, in <module>
    with dissove
NameError: name 'dissove' is not defined

Linux-5.4.0-64-generic-i686-with-debian-buster-sid
Ren'Py 7.4.1.1270
The Untold Path 1.0
Sat Jan 30 18:47:39 2021
